### PR TITLE
create form.json & form.ttl for eigenschappen tab

### PR DESCRIPTION
**Pull request by aatauil**
- Added fields for eigenschappen 
- checked for working crud

note: some fields are not in use yet. They have been appended with "TODO"

### CODE REVIEW

**Comment by Windvis** [comment]
I did a quick test and it does seem that values are being persisted, but I noticed that even though I changed the status, the "pill" in the top bar doesn't match the select value even after a page refresh. Any idea what might cause this? Could that be the cache service?

**Comment by aatauil** [comment]
@Windvis Yeah this is because the values in the form and the one you get in the toolbar are seperate. Form comes from ttl & lpdc-management service while the toolbar values come from resources. (90% sure of this)

**Comment by aatauil** [comment]
I dont think there is a ,non dirty , way to sync this. at least not 'live' so when a user changes the status and it reflecting without saving. When saving we could force a refresh for that routes model

**Comment by Windvis** [comment]
@aatauil [We already reload the record data after a save](https://github.com/lblod/frontend-loket/blob/feature/lpdc-module/app/components/public-services/details-form.js#L87) but the backend returns the old data again. I think we need to bust the cache for that specific record somehow, but I'm not sure that's possible from a custom micro service?

Maybe we can just ditch the cache for these resource types for now? As a quick fix.

**Comment by aatauil** [comment]
@Windvis yes, we decided for GET request to public-services to point directly to resources
see: https://github.com/lblod/app-digitaal-loket/commit/d77232f8ab0547e9daaa08a2a3b033477615868f
will test it right away

**Comment by aatauil** [comment]
@Windvis Discoverd the issue (frontend-related) So I noticed that indeed the frontend re-fetches the data but we missed something. In the original findRecord we use 'include' for the type and status. When you reload() the publicService model it will not re-fetch those relationships. 

We need to explicitly also reload those relationships
publicService.status.reload()
publicService.type.reload()
publicService.reload()

(unless ember-data has an easier way but didnt find it in the docs)

relevant files
- router: https://github.com/lblod/frontend-loket/blob/chore/delete-public-service/app/routes/public-services/details.js
- save function: https://github.com/lblod/frontend-loket/blob/chore/delete-public-service/app/components/public-services/details-form.js#L87

**Comment by Windvis** [comment]
@aatauil Ahh, good catch. I pushed a fix for that in this pr: https://github.com/lblod/frontend-loket/pull/124/commits/bbf058cf33d1592daff44a30366fa0b6a1e5e608 After that the status seems to properly update 👍.

I'm not a fan of manually reloading the relationships in the save method since that means we have to maintain the list in 2 places. Reloading the model hook of the details route seems like a better way to do it, but that would also show the loading template again and we can't tell Ember not to do that. So I went with a util instead. It could be changed to a service so we don't need to pass the store, but I thought I would keep it simple 😄.

**Pull request merged**
