### PR TITLE
cleanup legacy subsidies

### PR DESCRIPTION
**Pull request by wolfderechter**
## ID
DL-6087

## Description

Cleanup legacy subsidies services and  files

Todo:
- find and delete remaining subsidy related migrations for 2018-2022?
- check if loket is still running, spin up from scratch?

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Other

### CODE REVIEW

**Comment by Riadabd** [comment]
Found these migrations that can most likely be removed as well:
* `config/migrations/2022/20220414124741-fix-naming-inconsistency-plan-living-together-withdrawal-rule.sparql`
* `config/migrations/2023/20230224122141-update-opvolgmoment-deadline-for-LEKP-1-0.sparql`
* `config/migrations/2021/20210208091011-remove-doubled-aanvragen.sparql`
* `config/migrations/2021/20210329124350-add-concepts-for-contact-tracing.sparql`
* `config/migrations/2021/20210430134039-add-external-info-series.sparql`
* `config/migrations/2021/20210607104847-fix-multiple-statuses-on-smc.sparql`
* `config/migrations/2021/20210811163541-fix-duplicated-objective-table.sparql`
* `config/migrations/2021/20210812175522-fix-duplicated-objective-table.sparql`
* `config/migrations/2022/20220414124741-fix-naming-inconsistency-plan-living-together-withdrawal-rule.sparql`
* `config/migrations/2023/20230224122141-update-opvolgmoment-deadline-for-LEKP-1-0.sparql`
* `config/migrations/2023/20230404105700-stadsvernieuwing-phase-2-financierings-partners-concept-scheme.sparql`
* `config/migrations/2023/20230404170311-cleanup-empty-stadsvernieuwing-project-subsisdy-step-2.sparql`

Can you have a look at them as well? I don't think they have any non-subsidy elements but just want to double-check before removing them.

**Comment by wolfderechter** [comment]
> Can you have a look at them? I don't think they have any non-subsidy elements but just want to double-check before removing them.

I've deleted some more thanks for checking, the question now is if loket is still running fine. I've verified myself with qa data that things are still running but I'm not too familiar with all the modules

**Comment by Riadabd** [comment]
> I've deleted some more thanks for checking, the question now is if loket is still running fine. I've verified myself with qa data that things are still running but I'm not too familiar with all the modules

I've tried clicking around as well, and nothing seems to be broken. I'll try it again with a production backup to confirm there's no weird behavior.

**Review by Riadabd — APPROVED** [review]
Looks good!

Don't forget to edit the CHANGELOG.

**Pull request merged**
