### PR TITLE
Bump migrations service to v0.9.0

### PR DESCRIPTION
**Pull request by Riadabd**
## Description

Loket is still using `v0.6.0` of `mu-migrations-service`; this bumps it to `v0.9.0`.

### On your current setup

* Run `drc up -d migrations` on your current setup and check the logs for any weird output.

### From a fresh slate

You need to down the stack and reset your `data/db` folder first:

```sh
drc down
```

```sh
rm -rf data/db && git checkout data/db
```

Afterwards, start migrations:

```sh
drc up -d migrations
```

The process will take some time as it is running all migrations. Monitor the logs of the service to check if there is some anomaly.

### CODE REVIEW

**Comment by Riadabd** [comment]
Running the migrations service on a fresh db errors out on `config/migrations/2020/20200311144300-update-forms/20200311145302-update-dynamic-forms-insert-updated-forms-forms-2018.ttl`:
* [First error](https://github.com/lblod/app-digitaal-loket/blob/fab8316a51e73e16f3af4a9218270dc3b63b74a6/config/migrations/2020/20200311144300-update-forms/20200311145302-update-dynamic-forms-insert-updated-forms-forms-2018.ttl#L1310-L1313)
* [Second error](https://github.com/lblod/app-digitaal-loket/blob/fab8316a51e73e16f3af4a9218270dc3b63b74a6/config/migrations/2020/20200311144300-update-forms/20200311145302-update-dynamic-forms-insert-updated-forms-forms-2018.ttl#L1455-L1458)
* [Third error](https://github.com/lblod/app-digitaal-loket/blob/fab8316a51e73e16f3af4a9218270dc3b63b74a6/config/migrations/2020/20200311144300-update-forms/20200311145302-update-dynamic-forms-insert-updated-forms-forms-2018.ttl#L1481-L1484)

They all seem to include a premature `;` before the end of the actual list.

**Comment by Riadabd** [comment]
Adjusting the colon and semi-colon order in the three aforementioned lines in the comment above fixes the issue, and the service runs all migrations inside the development branch without issues.

**Comment by cecemel** [comment]
@Riadabd i think we can merge this one right? Do still need to update the migrations themselves?

**Comment by Riadabd** [comment]
@cecemel I think we still need to update the migration file; otherwise, if someone wants to run the migrations from scratch, the service will exit when trying to run `config/migrations/2020/20200311144300-update-forms/20200311145302-update-dynamic-forms-insert-updated-forms-forms-2018.ttl`.

**Comment by Windvis** [comment]
I was able to finish the migrations after the changes (in about 1 hour) 🎉 .

**Pull request merged**
