### PR TITLE
Add urban renewal application second phase form skeleton

### PR DESCRIPTION
**Pull request by Riadabd**
(Addresses DL-4946) This adds the form skeleton for "Aanvraag (2e fase)" for the urban renewal subsidy.

To test:
1. Log in as "Gemeente" (I used "Gemeente Deinze" as reference)
2. Go to "Subsidiebeheer"
3. Search for "Stadsvernieuwing - projectsubsidie"
4. Open "Aanvraag (2e fase)" and check the form (the form's fields should be visible but inaccessible).
5. In order to access the fields, add dummy data to the first "Aanvraag" form and submit it.
6. The fields of "Aanvraag (2e fase)" should now be accessible and editable.

### CODE REVIEW

**Review by Poltergeistz — APPROVED** [review]
Looks good to me :+1:

**Comment by Windvis** [comment]
Should this target a feature branch instead? I don't think we want to deploy this unless the whole form is finished?

**Comment by aatauil** [comment]
@Windvis Indeed. @Riadabd could you create a feature branch `feature/stadsvernieuwing-fase-2`, change the target branch of this PR from development to the new feature branch and then merge ? Thanks ! :)

**Comment by Riadabd** [comment]
Done :)

**Pull request merged**
